const now=Date.now();
const alerts=[
{id:"heat-ie",version:"2026-07-22-1",title:"High-temperature health reference",category:"Weather health",severity:"high",summary:"High temperatures are affecting parts of Ireland. This manually maintained reference highlights hydration, shade and heat-stress precautions.",distance:0,coverage:"Ireland — verify local warning",confidenceLevel:"medium",confidence:"Reference alert — confirm with Met Éireann and HSE",observedAt:now-35*60*1000,retrievedAt:now-5*60*1000,expiresAt:now+6*60*60*1000,action:"Drink water now, avoid prolonged peak-heat exposure and check on vulnerable people.",source:"Met Éireann and HSE reference pages",url:"https://www.met.ie/",label:"CURRENT REFERENCE",placeQuery:"open grocery stores",routeQuery:"shaded parks and indoor public places"},
{id:"air-demo",version:"2026-07-22-1",title:"Air-quality KPI foundation",category:"Air quality",severity:"moderate",summary:"The dashboard page contains AQI/AQIH plus PM2.5, PM10, NO₂, O₃ and CO indicators.",distance:3.2,coverage:"Demonstration only",confidenceLevel:"low",confidence:"Not scored — no live feed",observedAt:now-90*60*1000,retrievedAt:now-10*60*1000,expiresAt:now+2*60*60*1000,action:"Check the nearest official monitoring station before changing outdoor activity.",source:"EPA Ireland — Air Quality",url:"https://airquality.ie/",label:"DEMO · KPI VIEW",placeQuery:"indoor public places",routeQuery:"parks and low traffic walking routes"},
{id:"weather-demo",version:"2026-07-22-1",title:"Weather-health monitoring foundation",category:"Weather health",severity:"low",summary:"Shows future heat, cold, UV and severe-weather relevance using official forecasts and public guidance.",distance:0,coverage:"Region",confidenceLevel:"low",confidence:"Not scored — no live feed",observedAt:now-70*60*1000,retrievedAt:now-12*60*1000,expiresAt:now+3*60*60*1000,action:"Review the latest official forecast before travelling or exercising outdoors.",source:"Met Éireann",url:"https://www.met.ie/",label:"DEMO · REFERENCE",placeQuery:"indoor activities",routeQuery:"covered walking routes"},
{id:"public-health-demo",version:"2026-07-22-1",title:"Public-health notice foundation",category:"Infectious disease",severity:"low",summary:"Shows how official notices will be filtered by date, geography and public relevance.",distance:0,coverage:"Ireland",confidenceLevel:"low",confidence:"Not scored — no live feed",observedAt:now-4*60*60*1000,retrievedAt:now-25*60*1000,expiresAt:now+12*60*60*1000,action:"Use current HSE or HPSC guidance and consult a professional for personal concerns.",source:"Health Protection Surveillance Centre",url:"https://www.hpsc.ie/",label:"DEMO · REFERENCE",placeQuery:"pharmacies",routeQuery:"health centres"}
];

const locationInput=document.querySelector("#location"),radius=document.querySelector("#radius"),radiusValue=document.querySelector("#radiusValue"),radiusMetric=document.querySelector("#radiusMetric"),areaMetric=document.querySelector("#areaMetric"),signalMetric=document.querySelector("#signalMetric"),alertGrid=document.querySelector("#alertGrid"),checkedMetric=document.querySelector("#checkedMetric"),locationStatus=document.querySelector("#locationStatus"),locateButton=document.querySelector("#locateButton"),notificationToggle=document.querySelector("#notificationToggle"),notificationStatus=document.querySelector("#notificationStatus"),groceriesLink=document.querySelector("#groceriesLink");
let currentCoordinates=null;

function safeText(value){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));}
function relativeTime(timestamp){const minutes=Math.max(0,Math.round((Date.now()-timestamp)/60000));if(minutes<60)return `${minutes} min ago`;const hours=Math.round(minutes/60);return `${hours} hr${hours===1?"":"s"} ago`;}
function freshness(alert){if(Date.now()>alert.expiresAt)return {label:"Expired",className:"expired"};const age=Date.now()-alert.observedAt;if(age<=60*60*1000)return {label:"Fresh",className:"fresh"};if(age<=3*60*60*1000)return {label:"Ageing",className:"ageing"};return {label:"Stale",className:"stale"};}
function mapSearch(query){if(currentCoordinates)return `https://www.google.com/maps/search/${encodeURIComponent(query)}/@${currentCoordinates.latitude},${currentCoordinates.longitude},14z`;return `https://www.google.com/maps/search/${encodeURIComponent(query+" near "+(locationInput.value.trim()||"Ireland"))}`;}
function updateGroceriesLink(){groceriesLink.href=mapSearch("open grocery stores");}
function render(){const km=Number(radius.value),visible=alerts.filter(a=>a.distance<=km&&Date.now()<=a.expiresAt);radiusValue.textContent=km;radiusMetric.textContent=`${km} km`;areaMetric.textContent=locationInput.value.trim()||"Nearby town or city";signalMetric.textContent=visible.length;checkedMetric.textContent=new Intl.DateTimeFormat([], {hour:"2-digit",minute:"2-digit"}).format(new Date());alertGrid.innerHTML=visible.map(a=>{const fresh=freshness(a);return `<article class="alert-card ${a.severity==='high'?'high-alert-card':''}"><div class="alert-top"><span class="severity ${a.severity}">${safeText(a.severity)}</span><span class="label">${safeText(a.label)}</span></div><div class="status-row"><span class="status-pill ${fresh.className}">${fresh.label}</span><span class="status-pill confidence-${a.confidenceLevel}">${safeText(a.confidenceLevel)} confidence</span></div><h3>${safeText(a.title)}</h3><p>${safeText(a.summary)}</p><p class="action"><strong>Do this now:</strong> ${safeText(a.action)}</p><div class="alert-actions"><a class="mini-action primary" href="${mapSearch(a.placeQuery)}" target="_blank" rel="noopener">Nearby support ↗</a><a class="mini-action" href="${mapSearch(a.routeQuery)}" target="_blank" rel="noopener">Safer alternative ↗</a></div><details class="alert-details"><summary>Why this alert and data details</summary><dl><div><dt>Coverage</dt><dd>${safeText(a.coverage)}</dd></div><div><dt>Observed</dt><dd>${relativeTime(a.observedAt)}</dd></div><div><dt>Retrieved</dt><dd>${relativeTime(a.retrievedAt)}</dd></div><div><dt>Confidence</dt><dd>${safeText(a.confidence)}</dd></div></dl><a class="source-link" href="${a.url}" target="_blank" rel="noopener">Open ${safeText(a.source)} ↗</a></details></article>`;}).join("")||'<p>No current signals fall inside this radius.</p>';updateGroceriesLink();}

function alertFingerprint(alert){return `${alert.id}:${alert.version}:${alert.severity}`;}
function showPriorityNotifications(){if(!("Notification" in window)||Notification.permission!=="granted")return;alerts.filter(a=>a.severity==="high"&&Date.now()<=a.expiresAt).forEach(alert=>{const key=`swasthyaAlert:${alert.id}`;const previous=localStorage.getItem(key);const fingerprint=alertFingerprint(alert);if(previous===fingerprint)return;new Notification(`Swasthya: ${alert.title}`,{body:alert.action,tag:alert.id});localStorage.setItem(key,fingerprint);});}
async function setNotifications(enabled){if(!enabled){localStorage.setItem("swasthyaNotifications","off");notificationStatus.textContent="Notifications are off.";return;}if(!("Notification" in window)){notificationToggle.checked=false;notificationStatus.textContent="This browser does not support website notifications.";return;}const permission=await Notification.requestPermission();if(permission==="granted"){localStorage.setItem("swasthyaNotifications","on");notificationStatus.textContent="Notifications are on. You will only be alerted for new or materially changed high-priority signals.";showPriorityNotifications();}else{notificationToggle.checked=false;localStorage.setItem("swasthyaNotifications","off");notificationStatus.textContent="Notification permission was not granted. You can enable it later in browser settings.";}}

radius.addEventListener("input",render);locationInput.addEventListener("input",()=>{currentCoordinates=null;render();});notificationToggle.addEventListener("change",()=>setNotifications(notificationToggle.checked));
locateButton.addEventListener("click",()=>{if(!navigator.geolocation){locationStatus.textContent="Location is not supported by this browser.";return;}locateButton.disabled=true;locationStatus.textContent="Requesting browser permission…";navigator.geolocation.getCurrentPosition(({coords})=>{currentCoordinates={latitude:coords.latitude,longitude:coords.longitude};const lat=coords.latitude.toFixed(2),lon=coords.longitude.toFixed(2);locationInput.value=`Nearby region (${lat}, ${lon})`;locationStatus.textContent="Approximate coordinates are used locally for nearby searches and are not stored by this static page.";locateButton.disabled=false;render();},()=>{locationStatus.textContent="Location permission was unavailable. Enter a nearby town or city instead.";locateButton.disabled=false;},{enableHighAccuracy:false,timeout:8000,maximumAge:300000});});

const notificationsEnabled=localStorage.getItem("swasthyaNotifications")==="on";notificationToggle.checked=notificationsEnabled&&("Notification" in window)&&Notification.permission==="granted";if(notificationToggle.checked){notificationStatus.textContent="Notifications are on. Only new or materially changed high-priority signals will appear.";showPriorityNotifications();}
render();
