const alerts=[
{title:"High-temperature health reference",category:"Weather health",severity:"high",summary:"High temperatures are affecting parts of Ireland. This manually maintained reference alert highlights hydration, shade and heat-stress precautions.",distance:0,coverage:"Ireland — check official local warning",confidence:"Reference alert — verify with Met Éireann and HSE",action:"Drink water regularly, choose hydrating foods, avoid prolonged peak-heat exposure and check on vulnerable people.",source:"Met Éireann and HSE reference pages",url:"https://www.met.ie/",label:"CURRENT REFERENCE"},
{title:"Air-quality KPI foundation",category:"Air quality",severity:"moderate",summary:"The air-quality dashboard now surfaces AQI/AQIH plus PM2.5, PM10, NO₂, O₃ and CO rather than a generic air-quality label.",distance:3.2,coverage:"Demonstration only",confidence:"Not scored — no live feed",action:"Check the nearest official monitoring station and follow existing clinical advice for respiratory conditions.",source:"EPA Ireland — Air Quality",url:"https://airquality.ie/",label:"DEMO · KPI VIEW"},
{title:"Weather-health monitoring foundation",category:"Weather health",severity:"low",summary:"Shows future heat, cold, UV and severe-weather health relevance using official forecasts and public guidance.",distance:0,coverage:"Region",confidence:"Not scored — no live feed",action:"Review current official forecasts and any active public warnings.",source:"Met Éireann",url:"https://www.met.ie/",label:"DEMO · REFERENCE"},
{title:"Public-health notice foundation",category:"Infectious disease",severity:"low",summary:"Shows how official infectious-disease notices will be filtered by date, geography and public relevance.",distance:0,coverage:"Ireland",confidence:"Not scored — no live feed",action:"Use current HSE or HPSC guidance and consult a professional for personal concerns.",source:"Health Protection Surveillance Centre",url:"https://www.hpsc.ie/",label:"DEMO · REFERENCE"}
];

const locationInput=document.querySelector("#location"),radius=document.querySelector("#radius"),radiusValue=document.querySelector("#radiusValue"),radiusMetric=document.querySelector("#radiusMetric"),areaMetric=document.querySelector("#areaMetric"),signalMetric=document.querySelector("#signalMetric"),alertGrid=document.querySelector("#alertGrid"),checkedMetric=document.querySelector("#checkedMetric"),locationStatus=document.querySelector("#locationStatus"),locateButton=document.querySelector("#locateButton"),notificationToggle=document.querySelector("#notificationToggle"),notificationStatus=document.querySelector("#notificationStatus"),groceriesLink=document.querySelector("#groceriesLink");
let currentCoordinates=null;
function safeText(value){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));}
function updateGroceriesLink(){if(currentCoordinates){groceriesLink.href=`https://www.google.com/maps/search/open+grocery+stores/@${currentCoordinates.latitude},${currentCoordinates.longitude},14z`;return;}const place=encodeURIComponent(locationInput.value.trim()||"Ireland");groceriesLink.href=`https://www.google.com/maps/search/open+grocery+stores+near+${place}`;}
function render(){const km=Number(radius.value),visible=alerts.filter(a=>a.distance<=km);radiusValue.textContent=km;radiusMetric.textContent=`${km} km`;areaMetric.textContent=locationInput.value.trim()||"Nearby town or city";signalMetric.textContent=visible.length;checkedMetric.textContent=new Intl.DateTimeFormat([], {hour:"2-digit",minute:"2-digit"}).format(new Date());alertGrid.innerHTML=visible.map(a=>`<article class="alert-card ${a.severity==='high'?'high-alert-card':''}"><div class="alert-top"><span class="severity ${a.severity}">${safeText(a.severity)}</span><span class="label">${safeText(a.label)}</span></div><h3>${safeText(a.title)}</h3><p>${safeText(a.summary)}</p><p class="action"><strong>Suggested action:</strong> ${safeText(a.action)}</p><div class="metadata">${a.distance} km · ${safeText(a.coverage)}<br>Confidence: ${safeText(a.confidence)}</div><a class="source-link" href="${a.url}" target="_blank" rel="noopener">${safeText(a.source)} ↗</a></article>`).join("")||'<p>No signals fall inside this radius.</p>';updateGroceriesLink();}
function showPriorityNotification(){if(!("Notification" in window)||Notification.permission!=="granted")return;const lastShown=Number(localStorage.getItem("swasthyaLastHeatNotice")||0),sixHours=21600000;if(Date.now()-lastShown<sixHours)return;new Notification("Swasthya: high-temperature health reference",{body:"Drink water regularly, avoid prolonged peak-heat exposure and check official Met Éireann and HSE advice.",tag:"swasthya-heat-reference"});localStorage.setItem("swasthyaLastHeatNotice",String(Date.now()));}
async function setNotifications(enabled){if(!enabled){localStorage.setItem("swasthyaNotifications","off");notificationStatus.textContent="Notifications are off.";return;}if(!("Notification" in window)){notificationToggle.checked=false;notificationStatus.textContent="This browser does not support website notifications.";return;}const permission=await Notification.requestPermission();if(permission==="granted"){localStorage.setItem("swasthyaNotifications","on");notificationStatus.textContent="Notifications are on for high-priority signals while this website is active.";showPriorityNotification();}else{notificationToggle.checked=false;localStorage.setItem("swasthyaNotifications","off");notificationStatus.textContent="Notification permission was not granted. You can enable it later in browser settings.";}}
radius.addEventListener("input",render);locationInput.addEventListener("input",()=>{currentCoordinates=null;render();});notificationToggle.addEventListener("change",()=>setNotifications(notificationToggle.checked));
locateButton.addEventListener("click",()=>{if(!navigator.geolocation){locationStatus.textContent="Location is not supported by this browser.";return;}locateButton.disabled=true;locationStatus.textContent="Requesting browser permission…";navigator.geolocation.getCurrentPosition(({coords})=>{currentCoordinates={latitude:coords.latitude,longitude:coords.longitude};const lat=coords.latitude.toFixed(2),lon=coords.longitude.toFixed(2);locationInput.value=`Nearby region (${lat}, ${lon})`;locationStatus.textContent="Approximate coordinates are shown locally and are not stored or transmitted by this static page.";locateButton.disabled=false;render();},()=>{locationStatus.textContent="Location permission was unavailable. Enter a nearby town or city instead.";locateButton.disabled=false;},{enableHighAccuracy:false,timeout:8000,maximumAge:300000});});

const conditionContent={
adhd:{title:"ADHD support check-in",description:"Notice how sleep, structure, focus load and stress are affecting your day.",actions:["Choose one clearly defined next task.","Reduce distractions for a short focus block.","Use a visible reminder or timer.","Seek an assessment from a qualified professional if difficulties are persistent and impairing."]},
epilepsy:{title:"Epilepsy wellbeing check-in",description:"Track general wellbeing factors that may be useful to discuss with your care team. This is not seizure prediction.",actions:["Take prescribed medication exactly as directed.","Protect regular sleep and avoid known personal triggers.","Record events or concerns for your clinical team.","Use emergency services for a prolonged seizure, repeated seizures without recovery or serious injury."]},
stress:{title:"Stress pattern check-in",description:"Notice whether demands, sleep and recovery are becoming difficult to manage.",actions:["Pause for slow breathing or a short walk.","Reduce the next task to a manageable step.","Talk to someone you trust.","Seek professional support when stress is persistent or affecting daily life."]},
mental:{title:"Mental wellbeing check-in",description:"Reflect on energy, routine, pressure and concentration without labelling or diagnosing yourself.",actions:["Keep one supportive routine today.","Connect with a trusted person.","Make time for food, water, rest and movement.","Use urgent support if you feel unable to stay safe."]}
};
const tabs=[...document.querySelectorAll(".condition-tab")],ranges=[...document.querySelectorAll(".checkin-range")],conditionTitle=document.querySelector("#conditionTitle"),conditionDescription=document.querySelector("#conditionDescription"),insightScore=document.querySelector("#insightScore"),insightText=document.querySelector("#insightText"),conditionActions=document.querySelector("#conditionActions");let activeCondition="adhd";
function updateCheckin(){ranges.forEach(r=>{const output=document.querySelector(`#${r.id.replace('Range','Value')}`);if(output)output.value=r.value;});const sleep=Number(document.querySelector("#sleepRange").value),stress=Number(document.querySelector("#stressRange").value),focus=Number(document.querySelector("#focusRange").value),routine=Number(document.querySelector("#routineRange").value);const pressure=(6-sleep)+stress+focus+(6-routine);let score="Balanced",text="Your check-in is mixed. Keep the day simple, protect sleep and use one clear next action.";if(pressure>=15){score="High load";text="Several pressures are elevated today. Reduce demands where possible and consider reaching out for support.";}else if(pressure<=9){score="Steady";text="Your current pattern looks relatively steady. Maintain the routines that are helping.";}insightScore.textContent=score;insightText.textContent=text;const content=conditionContent[activeCondition];conditionActions.innerHTML=content.actions.map(item=>`<div>${safeText(item)}</div>`).join("");}
function selectCondition(name){activeCondition=name;tabs.forEach(tab=>tab.classList.toggle("active",tab.dataset.condition===name));const content=conditionContent[name];conditionTitle.textContent=content.title;conditionDescription.textContent=content.description;updateCheckin();}
tabs.forEach(tab=>tab.addEventListener("click",()=>selectCondition(tab.dataset.condition)));ranges.forEach(range=>range.addEventListener("input",updateCheckin));

const notificationsEnabled=localStorage.getItem("swasthyaNotifications")==="on";notificationToggle.checked=notificationsEnabled&&("Notification" in window)&&Notification.permission==="granted";if(notificationToggle.checked){notificationStatus.textContent="Notifications are on for high-priority signals while this website is active.";showPriorityNotification();}
render();selectCondition("adhd");
